# Generated by Django 4.2.23 on 2025-07-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_creditor_profile_alter_debtor_slug'),
        ('client', '0006_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creditor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.creditor'),
        ),
    ]
