# Generated by Django 4.2.23 on 2025-08-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_profile_creditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='ach', max_length=30)),
                ('is_stripe_connected', models.BooleanField(default=False)),
                ('stripe_connect_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
