# Generated by Django 4.2.23 on 2025-08-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_withdrawalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsettings',
            name='login_link',
            field=models.CharField(default='', max_length=150),
        ),
    ]
