# Generated by Django 4.2.23 on 2025-08-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_withdrawalsettings_login_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsettings',
            name='ach_link',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='withdrawalsettings',
            name='is_ach_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalsettings',
            name='is_paypal_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawalsettings',
            name='paypal_link',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='withdrawalsettings',
            name='login_link',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
