# Generated by Django 4.2.23 on 2025-08-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_customsmstemplate_messagetemplaterouter'),
        ('client', '0012_issue_created_at_issue_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sms_template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.messagetemplaterouter'),
        ),
    ]
