# Generated by Django 4.2.23 on 2025-08-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_profile_sms_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sms_template',
        ),
    ]
