# Generated by Django 4.2.23 on 2025-07-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_creditor_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='unique_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
