# Generated by Django 4.2.23 on 2025-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_debtor_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='unique_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
