# Generated by Django 4.2.23 on 2025-07-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_profile_user'),
        ('main', '0003_scheduledmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='client.profile'),
        ),
    ]
