# Generated by Django 4.2.23 on 2025-07-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_creditor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='collecting',
            field=models.BooleanField(default=False),
        ),
    ]
