# Generated by Django 4.2.23 on 2025-07-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_debt_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_settled',
            field=models.BooleanField(default=False),
        ),
    ]
