# Generated by Django 4.2.23 on 2025-07-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_debt_collecting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
