# Generated by Django 4.2.23 on 2025-07-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_messagetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='debt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.debt'),
        ),
    ]
