# Generated by Django 4.2.23 on 2025-07-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_scheduledmessage_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='slug',
            field=models.SlugField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='unique_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
