# Generated by Django 4.2.23 on 2025-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_debtor_slug_alter_debtor_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditor',
            name='profile',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, null=True),
        ),
    ]
