# Generated by Django 4.2.23 on 2025-07-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_creditor_profile_alter_debtor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='is_stripe_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditor',
            name='stripe_connect_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
