# Generated by Django 4.2.23 on 2025-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_creditor_is_stripe_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='percent_cut',
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=5),
        ),
    ]
