# Generated by Django 4.2.23 on 2025-08-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_withdrawalsettings'),
        ('main', '0012_creditor_percent_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='withdrawals',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.withdrawalsettings'),
        ),
    ]
