# Generated by Django 4.2.23 on 2025-08-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('template', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplateRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router1', to='main.customsmstemplate')),
                ('followup2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router2', to='main.customsmstemplate')),
                ('initial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router_init', to='main.customsmstemplate')),
            ],
        ),
    ]
