# Generated by Django 4.2.23 on 2025-08-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_remove_profile_sms_template'),
        ('main', '0017_customsmstemplate_messagetemplaterouter'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplaterouter',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_router', to='client.profile'),
        ),
    ]
