# Generated by Django 4.2.23 on 2025-09-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCustomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='messagetemplaterouter',
            name='email_followup1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router1', to='main.emailcustomtemplate'),
        ),
        migrations.AddField(
            model_name='messagetemplaterouter',
            name='email_followup2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router2', to='main.emailcustomtemplate'),
        ),
        migrations.AddField(
            model_name='messagetemplaterouter',
            name='email_initial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router_init', to='main.emailcustomtemplate'),
        ),
    ]
