# Generated by Django 4.2.23 on 2025-09-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_emailcustomtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplaterouter',
            name='email_followup1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router1', to='main.emailcustomtemplate'),
        ),
        migrations.AlterField(
            model_name='messagetemplaterouter',
            name='email_followup2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router2', to='main.emailcustomtemplate'),
        ),
        migrations.AlterField(
            model_name='messagetemplaterouter',
            name='email_initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router_init', to='main.emailcustomtemplate'),
        ),
    ]
